[package]
name = "noa"
version = "0.1.0"
edition = "2021"

publish = true
authors = ["langyo <langyo.china@gmail.com>"]
description = "Next document generator for Rust crates"
license = "Apache-2.0"
repository = "https://github.com/celestia-island/noa"

[[bin]]
name = "noa"
path = "bin/main.rs"

[dependencies]
anyhow = "^1"
async-trait = "^0.1"
derive_more = { version = "^1", features = ["full"] }

serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
strum = { version = "^0.26", features = ["derive"] }
ron = "^0.8"
yuuka = "^0.5"

clap = "^4"

syn = { version = "^2", features = ["full"] }
proc-macro2 = { version = "^1", features = ["span-locations"] }
quote = "^1"
