packages:
  - packages/webui
  - ../hikari/packages/vue
  - ../plana/packages/rpc_client

allowBuilds:
  '@parcel/watcher': true

overrides:
  typescript: ~6.0

pnpm:
  overrides:
    "@celestia-island/hikari": link:../hikari/packages/vue
    "@celestia-island/plana-rpc-client": link:../plana/packages/rpc_client
