name: Clippy

on:
  pull_request:
    paths:
      - '.github/workflows/clippy.yml'
<<<<<<< HEAD
      - 'noa/**/*'
      - 'noa-macros/**/*'
      - 'Cargo.toml'
      - 'Cargo.lock'
  push:
    branches: [master]
=======
      - 'src/**/*'
      - 'bin/**/*'
      - 'Cargo.toml'
      - 'Cargo.lock'
  push:
    branches: [master, dev]
>>>>>>> origin/dev

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable
          - nightly

    steps:
      - uses: actions/checkout@v4

      - name: Setup toolchain
<<<<<<< HEAD
        uses: dtolnay/rust-toolchain@master
=======
        uses: dtolnay/rust-toolchain@stable
>>>>>>> origin/dev
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy

      - uses: Swatinem/rust-cache@v2

      - name: Run clippy
        run: |
          cargo clippy \
            --all-targets \
            --all-features \
            --workspace \
            -- -D warnings
