name: Format
on:
  pull_request:
    paths:
<<<<<<< HEAD
      - '.github/workflows/fmt.yml'
      - 'src/**/*'
      - 'bin/**/*'
      - 'scripts/**/*'
      - 'Cargo.toml'
      - 'Cargo.lock'
  push:
    branches: [master, dev]
=======
<<<<<<< HEAD
      - '.github/workflows/clippy.yml'
      - 'noa/**/*'
      - 'noa-macros/**/*'
      - 'Cargo.toml'
      - 'Cargo.lock'
  push:
    branches: [master]
=======
      - '.github/workflows/fmt.yml'
      - 'src/**/*'
      - 'bin/**/*'
      - 'scripts/**/*'
      - 'Cargo.toml'
      - 'Cargo.lock'
  push:
    branches: [master, dev]
>>>>>>> origin/dev
>>>>>>> origin/dev

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup toolchain
<<<<<<< HEAD
        uses: dtolnay/rust-toolchain@master
=======
        uses: dtolnay/rust-toolchain@stable
>>>>>>> origin/dev
        with:
          toolchain: nightly
          components: rustfmt

<<<<<<< HEAD
      - name: Check import group ordering
        run: python3 scripts/utils/enforce_use_groups.py --test

      - name: Run cargo fmt
=======
<<<<<<< HEAD
      - name: Run fmt
=======
      - name: Check import group ordering
        run: python3 scripts/utils/enforce_use_groups.py --test

      - name: Check markdown formatting
        run: python3 scripts/utils/format_markdown.py . --check

      - name: Run cargo fmt
>>>>>>> origin/dev
>>>>>>> origin/dev
        run: cargo +nightly fmt --all -- --check --unstable-features
